version: '3.8' # Specify the Compose file format version

services:
  screwdriver: # Define a service named 'screwdriver'
    build: .
    container_name: screwdriver
    ports:
      - "8000:8000"
    volumes:
      - ./:/root/src_dir # Mount the current directory as a volume inside the container at /src_dir
      - ./.workdir:/root/workdir
      - ./configuration.nix:/etc/nixos/configuration.nix
    working_dir: /root/src_dir

    command: >
        bash -c "cd /root/src_dir && pip install "fastapi[standard]"
        && fastapi dev main.py --host 0.0.0.0 --port 8000"
    environment:
       - NIX_PATH=nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
        # deploy:
        #     resources:
        #         reservations:
        #             devices:
        #                 - driver: nvidia
        #                   count: 1
        #                   capabilities: [gpu]
