---
_target_: lightning.Trainer
accelerator: auto
strategy: auto
devices: auto
num_nodes: 1
precision: bf16-mixed
fast_dev_run: false
max_epochs: ${epochs}
min_epochs:
max_steps: -1
min_steps:
max_time:
limit_train_batches:
limit_val_batches:
limit_test_batches:
limit_predict_batches:
overfit_batches: 0.0
val_check_interval: 1.0
check_val_every_n_epoch: 1
num_sanity_val_steps: 2
log_every_n_steps: 50
enable_checkpointing:
enable_progress_bar: true
enable_model_summary: true
accumulate_grad_batches: 1
gradient_clip_val: 1.0
gradient_clip_algorithm: norm
deterministic: false
benchmark: false
inference_mode: true
use_distributed_sampler: true
detect_anomaly: false
barebones: false
sync_batchnorm: false
reload_dataloaders_every_n_epochs: 0
default_root_dir:
logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir: ${logroot}
  name: ${experiment}
profiler:
  _target_: lightning.pytorch.profilers.SimpleProfiler
  filename: profiler
callbacks:
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    filename: best
    monitor: ${monitor_metric}
    save_top_k: 1
    mode: ${monitor_mode}
    auto_insert_metric_name: false
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    filename: last
    auto_insert_metric_name: false
    every_n_epochs: 1
  - _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: epoch
